# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import kv_pb2 as kv__pb2


class KVStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Get = channel.unary_unary(
        '/KV/Get',
        request_serializer=kv__pb2.Data.SerializeToString,
        response_deserializer=kv__pb2.Data.FromString,
        )
    self.Put = channel.unary_unary(
        '/KV/Put',
        request_serializer=kv__pb2.Data.SerializeToString,
        response_deserializer=kv__pb2.Data.FromString,
        )
    self.Delete = channel.unary_unary(
        '/KV/Delete',
        request_serializer=kv__pb2.Data.SerializeToString,
        response_deserializer=kv__pb2.Data.FromString,
        )
    self.GetLeader = channel.unary_unary(
        '/KV/GetLeader',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=kv__pb2.Node.FromString,
        )


class KVServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Put(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetLeader(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_KVServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=kv__pb2.Data.FromString,
          response_serializer=kv__pb2.Data.SerializeToString,
      ),
      'Put': grpc.unary_unary_rpc_method_handler(
          servicer.Put,
          request_deserializer=kv__pb2.Data.FromString,
          response_serializer=kv__pb2.Data.SerializeToString,
      ),
      'Delete': grpc.unary_unary_rpc_method_handler(
          servicer.Delete,
          request_deserializer=kv__pb2.Data.FromString,
          response_serializer=kv__pb2.Data.SerializeToString,
      ),
      'GetLeader': grpc.unary_unary_rpc_method_handler(
          servicer.GetLeader,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=kv__pb2.Node.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'KV', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
