# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='raft.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nraft.proto\"^\n\x0eRequestVoteReq\x12\x13\n\x0b\x63\x61ndidateId\x18\x01 \x01(\r\x12\x0c\n\x04term\x18\x02 \x01(\x04\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\r\x12\x13\n\x0blastLogTerm\x18\x04 \x01(\r\"3\n\x0eRequestVoteRes\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x13\n\x0bvoteGranted\x18\x02 \x01(\x08\"\x8e\x01\n\x10\x41ppendEntriesReq\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x10\n\x08leaderId\x18\x02 \x01(\r\x12\x14\n\x0cprevLogIndex\x18\x03 \x01(\r\x12\x13\n\x0bprevLogTerm\x18\x04 \x01(\x04\x12\x1a\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\t.LogEntry\x12\x13\n\x0b\x63ommitIndex\x18\x06 \x01(\r\"I\n\x10\x41ppendEntriesRes\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x16\n\x0elast_log_index\x18\x03 \x01(\r\"M\n\x0cPersistState\x12\x13\n\x0b\x63urrentTerm\x18\x01 \x01(\x04\x12\x10\n\x08votedFor\x18\x02 \x01(\r\x12\x16\n\x03log\x18\x03 \x03(\x0b\x32\t.LogEntry\"8\n\x07\x43ommand\x12\x11\n\toperation\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"B\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\r\n\x05index\x18\x02 \x01(\r\x12\x19\n\x07\x63ommand\x18\x03 \x01(\x0b\x32\x08.Command2t\n\x04raft\x12\x31\n\x0bRequestVote\x12\x0f.RequestVoteReq\x1a\x0f.RequestVoteRes\"\x00\x12\x39\n\rAppendEntries\x12\x11.AppendEntriesReq\x1a\x11.AppendEntriesRes\"\x00\x30\x01\x62\x06proto3')
)




_REQUESTVOTEREQ = _descriptor.Descriptor(
  name='RequestVoteReq',
  full_name='RequestVoteReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='candidateId', full_name='RequestVoteReq.candidateId', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='term', full_name='RequestVoteReq.term', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lastLogIndex', full_name='RequestVoteReq.lastLogIndex', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lastLogTerm', full_name='RequestVoteReq.lastLogTerm', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=108,
)


_REQUESTVOTERES = _descriptor.Descriptor(
  name='RequestVoteRes',
  full_name='RequestVoteRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='term', full_name='RequestVoteRes.term', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='voteGranted', full_name='RequestVoteRes.voteGranted', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=161,
)


_APPENDENTRIESREQ = _descriptor.Descriptor(
  name='AppendEntriesReq',
  full_name='AppendEntriesReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='term', full_name='AppendEntriesReq.term', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='leaderId', full_name='AppendEntriesReq.leaderId', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prevLogIndex', full_name='AppendEntriesReq.prevLogIndex', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prevLogTerm', full_name='AppendEntriesReq.prevLogTerm', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entries', full_name='AppendEntriesReq.entries', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='commitIndex', full_name='AppendEntriesReq.commitIndex', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=306,
)


_APPENDENTRIESRES = _descriptor.Descriptor(
  name='AppendEntriesRes',
  full_name='AppendEntriesRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='term', full_name='AppendEntriesRes.term', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='success', full_name='AppendEntriesRes.success', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_log_index', full_name='AppendEntriesRes.last_log_index', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=308,
  serialized_end=381,
)


_PERSISTSTATE = _descriptor.Descriptor(
  name='PersistState',
  full_name='PersistState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='currentTerm', full_name='PersistState.currentTerm', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='votedFor', full_name='PersistState.votedFor', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='log', full_name='PersistState.log', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=383,
  serialized_end=460,
)


_COMMAND = _descriptor.Descriptor(
  name='Command',
  full_name='Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='operation', full_name='Command.operation', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='Command.key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Command.value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=462,
  serialized_end=518,
)


_LOGENTRY = _descriptor.Descriptor(
  name='LogEntry',
  full_name='LogEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='term', full_name='LogEntry.term', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index', full_name='LogEntry.index', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='command', full_name='LogEntry.command', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=520,
  serialized_end=586,
)

_APPENDENTRIESREQ.fields_by_name['entries'].message_type = _LOGENTRY
_PERSISTSTATE.fields_by_name['log'].message_type = _LOGENTRY
_LOGENTRY.fields_by_name['command'].message_type = _COMMAND
DESCRIPTOR.message_types_by_name['RequestVoteReq'] = _REQUESTVOTEREQ
DESCRIPTOR.message_types_by_name['RequestVoteRes'] = _REQUESTVOTERES
DESCRIPTOR.message_types_by_name['AppendEntriesReq'] = _APPENDENTRIESREQ
DESCRIPTOR.message_types_by_name['AppendEntriesRes'] = _APPENDENTRIESRES
DESCRIPTOR.message_types_by_name['PersistState'] = _PERSISTSTATE
DESCRIPTOR.message_types_by_name['Command'] = _COMMAND
DESCRIPTOR.message_types_by_name['LogEntry'] = _LOGENTRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestVoteReq = _reflection.GeneratedProtocolMessageType('RequestVoteReq', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTVOTEREQ,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:RequestVoteReq)
  })
_sym_db.RegisterMessage(RequestVoteReq)

RequestVoteRes = _reflection.GeneratedProtocolMessageType('RequestVoteRes', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTVOTERES,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:RequestVoteRes)
  })
_sym_db.RegisterMessage(RequestVoteRes)

AppendEntriesReq = _reflection.GeneratedProtocolMessageType('AppendEntriesReq', (_message.Message,), {
  'DESCRIPTOR' : _APPENDENTRIESREQ,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:AppendEntriesReq)
  })
_sym_db.RegisterMessage(AppendEntriesReq)

AppendEntriesRes = _reflection.GeneratedProtocolMessageType('AppendEntriesRes', (_message.Message,), {
  'DESCRIPTOR' : _APPENDENTRIESRES,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:AppendEntriesRes)
  })
_sym_db.RegisterMessage(AppendEntriesRes)

PersistState = _reflection.GeneratedProtocolMessageType('PersistState', (_message.Message,), {
  'DESCRIPTOR' : _PERSISTSTATE,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:PersistState)
  })
_sym_db.RegisterMessage(PersistState)

Command = _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:Command)
  })
_sym_db.RegisterMessage(Command)

LogEntry = _reflection.GeneratedProtocolMessageType('LogEntry', (_message.Message,), {
  'DESCRIPTOR' : _LOGENTRY,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:LogEntry)
  })
_sym_db.RegisterMessage(LogEntry)



_RAFT = _descriptor.ServiceDescriptor(
  name='raft',
  full_name='raft',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=588,
  serialized_end=704,
  methods=[
  _descriptor.MethodDescriptor(
    name='RequestVote',
    full_name='raft.RequestVote',
    index=0,
    containing_service=None,
    input_type=_REQUESTVOTEREQ,
    output_type=_REQUESTVOTERES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AppendEntries',
    full_name='raft.AppendEntries',
    index=1,
    containing_service=None,
    input_type=_APPENDENTRIESREQ,
    output_type=_APPENDENTRIESRES,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RAFT)

DESCRIPTOR.services_by_name['raft'] = _RAFT

# @@protoc_insertion_point(module_scope)
